### ISSUE TITLE
support graalvm native image

### ISSUE THREAD

**Issue by 10000-ki** [mockito/mockito-kotlin#471] opened 2023-01-01 13:22 UTC
hi i am using graalvm native image in my project

and i found mockito in graalvm native image has some problems

- define proxy class in build time
```
 Proxy class defined by interfaces [interface org.mockito.plugins.PluginSwitch] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
       org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
       org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:171)
       java.base@17.0.5/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:47)
       java.base@17.0.5/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1037)
       org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:81)
       org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:54)
       org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:20)
       org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:20)
       org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:28)
       org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
       [...]
```

- reflection fail for org.mockito.internal.util.MockUtil 

```
  JUnit Jupiter:SymbolicatorClientApplicationTest:executeList()
    MethodSource [className = 'com.naver.nelo.ncrashlytics.SymbolicatorClientApplicationTest', methodName = 'executeList', methodParameterTypes = '']
    => java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.util.MockUtil
       org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
       org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:250)
       org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:232)
       org.mockito.internal.MockitoCore.mock(MockitoCore.java:83)
       org.mockito.Mockito.mock(Mockito.java:1956)
       java.base@17.0.5/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
       java.base@17.0.5/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
       org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:552)
       org.junit.jupiter.engine.execution.ConstructorInvocation.proceed(ConstructorInvocation.java:56)
```

I think the above issues are  arising from the `AOT compile`

I can apply some of the settings suggested by the native image

but I think it would be good to support the native image in mockito, do you have any plans?

**Comment by TimvdLippe** [comment] 2023-01-01 16:19
Duplicate of https://github.com/mockito/mockito/issues/2435

**Closed by TimvdLippe** 2023-01-01 16:19 UTC
